[package]
name = "rwlock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0"
core_affinity = "0.5"

[profile.release-lto]
inherits = "release"
overflow-checks = false
lto = true